name: Update Directory on Merge

on:
  # This workflow is triggered by pull requests to the main branch
  # from a forked repository. It runs in the context of the base
  # repository, which grants it the necessary permissions.
  pull_request_target:
    types: [closed]

jobs:
  update_directory:
    # This job only runs if the pull request was merged.
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    
    # CRITICAL: This is required to grant the `GITHUB_TOKEN` write permissions
    # for this specific job, allowing the `git push` command to succeed.
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        # The `pull_request_target` event only grants write permissions
        # to the base branch. By explicitly checking out the base branch,
        # we ensure the workflow has the correct permissions to push changes.
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Rebuild README.md
        # This step uses a multi-line shell script to run the logic directly
        # inside the GitHub Actions runner, without a separate Docker container.
        # This is more efficient and avoids authentication issues.
        run: |
          set -evx
          
          # Navigate to the people directory
          cd people/
          
          # Blow away the old README.md and rebuild it from scratch
          touch ../README.md
          
          # Get total entry count
          COUNT=$(ls -al | wc -l)
          COUNT=$((COUNT - 4))
          
          # Add the README boilerplate
          echo "# ds_2002-directory" > ../README.md
          echo "" >> ../README.md
          echo "A people directory for DS2002 ($COUNT people)" >> ../README.md
          echo "" >> ../README.md
          
          # Fetch name of each person and build the list
          for dir in */; do
              if [ -d "$dir" ]; then
                  NAME=$(head -1 "$dir/README.md" | sed -e 's/#//g;')
                  plaindir=${dir%/}
                  echo "- **$plaindir** - [$NAME](people/$dir)" >> ../README.md
              fi
          done

      - name: Commit and Push Changes
        # This block commits the updated README.md and pushes it back to the repository.
        # The GITHUB_TOKEN is a temporary token automatically provided by GitHub Actions.
        run: |
          # Configure Git with a user name and email for the commit
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Check for changes using --porcelain for clean output
          if [ -z "$(git status --porcelain)" ]; then  
            echo "No changes to commit. Exiting."
            exit 0
          else
            echo "Changes found. Committing and pushing."
            git add README.md
            git commit -m "Updated directory after merge"
            git push
          fi
